import{buildStableHash}from"../application-harness/fingerprints";
import type{CandidateFactV1,CandidateFactTypeV1}from"../candidate-evidence/schema";
import type{AllowedClaimTypeV1,AllowedClaimV1,EvidenceGraphBuildInputV1,EvidenceGraphV1,EvidenceMatchReviewStateV1,EvidenceMatchV1,JobDemandV1,MissingEvidenceV1}from"./schema";
import{buildRiskFlags,determineFactDemandMatchType,getSourceGroundedClaimText,isApprovedUseInApplicationsFact,slug}from"./riskRules";
export{buildRiskFlags}from"./riskRules";
const NS="evidence-graph";
type GraphHashes=Readonly<{jobDemandGraphHash:string;candidateEvidenceHash:string;careerKnowledgeHash:string}>;
export async function buildEvidenceGraph(i:EvidenceGraphBuildInputV1):Promise<EvidenceGraphV1>{ok(i);const demands=sd(i.demands),matches=matchCandidateFactsToDemands(i),missing=buildMissingEvidence(demands,matches,i.candidateFacts),riskFlags=buildRiskFlags(i),allowedClaims=buildAllowedClaims(i,matches),blockedClaimIds=blocked(i,allowedClaims,matches);const hashes=await buildEvidenceGraphSubHashes(i),h=await buildEvidenceGraphHashFromSubHashes(i,hashes);return{id:`evidence-graph:${h}`,userId:i.userId,applicationContextId:i.applicationContextId,jobDemandGraphHash:hashes.jobDemandGraphHash,candidateEvidenceHash:hashes.candidateEvidenceHash,careerKnowledgeHash:hashes.careerKnowledgeHash,demands,matches,missing,riskFlags,allowedClaims,blockedClaimIds,createdAt:i.createdAt,version:1}}
export async function buildEvidenceGraphHash(i:EvidenceGraphBuildInputV1):Promise<string>{ok(i);return buildEvidenceGraphHashFromSubHashes(i,await buildEvidenceGraphSubHashes(i))}
async function buildEvidenceGraphSubHashes(i:EvidenceGraphBuildInputV1):Promise<GraphHashes>{const[jobDemandGraphHash,candidateEvidenceHash,careerKnowledgeHash]=await Promise.all([buildJobDemandGraphHash(i.demands),buildCandidateEvidenceSelectionHash(i.candidateFacts),buildCareerKnowledgeSelectionHash(i.careerKnowledgeRules)]);return{jobDemandGraphHash,candidateEvidenceHash,careerKnowledgeHash}}
function buildEvidenceGraphHashFromSubHashes(i:EvidenceGraphBuildInputV1,h:GraphHashes):Promise<string>{return buildStableHash({namespace:NS,type:"evidence-graph",version:1,input:{userId:i.userId,applicationContextId:i.applicationContextId,...h}})}
export function buildJobDemandGraphHash(d:readonly JobDemandV1[]):Promise<string>{return buildStableHash({namespace:NS,type:"job-demand-graph",version:1,demands:sd(d)})}
export function buildCandidateEvidenceSelectionHash(f:readonly CandidateFactV1[]):Promise<string>{return buildStableHash({namespace:NS,type:"candidate-evidence-selection",version:1,candidateFacts:sf(f)})}
export function buildCareerKnowledgeSelectionHash(r:EvidenceGraphBuildInputV1["careerKnowledgeRules"]):Promise<string>{return buildStableHash({namespace:NS,type:"career-knowledge-selection",version:1,rules:[...r].sort((a,b)=>a.id.localeCompare(b.id))})}
export function matchCandidateFactsToDemands(i:EvidenceGraphBuildInputV1):readonly EvidenceMatchV1[]{const out:EvidenceMatchV1[]=[];for(const d of sd(i.demands))for(const f of sf(i.candidateFacts)){const mt=determineFactDemandMatchType(d,f);if(!mt)continue;out.push({id:["evidence-match",d.id,f.id,mt].map(slug).join(":"),demandId:d.id,candidateFactId:f.id,sourceDocumentId:f.sourceDocumentId,sourcePath:f.sourcePath,matchType:mt,strength:mt==="direct"?"strong":"medium",reviewState:state(f),reason:mt==="direct"?"Candidate fact directly matches the normalized demand label.":"Candidate fact shares deterministic normalized tokens with the demand label.",version:1})}return out.sort((a,b)=>a.id.localeCompare(b.id))}
export function buildMissingEvidence(d:readonly JobDemandV1[],m:readonly EvidenceMatchV1[],facts:readonly CandidateFactV1[]=[]):readonly MissingEvidenceV1[]{const ok=new Set(m.filter(x=>x.reviewState==="accepted").map(x=>x.demandId)),excluded=new Set(facts.filter(x=>x.visibility==="private"||x.visibility==="never_use").map(x=>x.id)),blocked=new Set(m.filter(x=>excluded.has(x.candidateFactId)).map(x=>x.demandId));return sd(d).filter(x=>!ok.has(x.id)&&!blocked.has(x.id)).map(x=>({id:`missing-evidence:${x.id}`,demandId:x.id,label:x.label,severity:x.required==="required"?"blocker":x.required==="preferred"?"warning":"info",reason:"No approved source-backed evidence matched this demand.",version:1}))}
export function buildAllowedClaims(i:EvidenceGraphBuildInputV1,m:readonly EvidenceMatchV1[]=matchCandidateFactsToDemands(i)):readonly AllowedClaimV1[]{const by=new Set(m.filter(x=>x.reviewState==="accepted").map(x=>x.candidateFactId));return sf(i.candidateFacts).filter(f=>by.has(f.id)&&isApprovedUseInApplicationsFact(f)).map(f=>({id:`allowed-claim:${f.id}`,candidateFactIds:[f.id],claimType:claim(f.factType),text:getSourceGroundedClaimText(f)??"",supportLevel:"strong" as const,reviewState:"allowed" as const,reason:"Approved use_in_applications candidate fact is source-grounded and matched a demand.",version:1 as const})).filter(c=>c.text).sort((a,b)=>a.id.localeCompare(b.id))}
function blocked(i:EvidenceGraphBuildInputV1,c:readonly AllowedClaimV1[],m:readonly EvidenceMatchV1[]):readonly string[]{const a=new Set(c.flatMap(x=>x.candidateFactIds)),matched=new Set(m.map(x=>x.candidateFactId));return sf(i.candidateFacts).filter(f=>matched.has(f.id)&&!a.has(f.id)).map(f=>`blocked-claim:${f.id}`)}
function state(f:CandidateFactV1):EvidenceMatchReviewStateV1{return isApprovedUseInApplicationsFact(f)?"accepted":f.reviewState==="rejected"||f.visibility==="never_use"?"rejected":"pending"}
function claim(t:CandidateFactTypeV1):AllowedClaimTypeV1{return t==="skill"||t==="experience"||t==="achievement"||t==="education"||t==="language"||t==="certification"||t==="project"?t:"other"}
function sd(a:readonly JobDemandV1[]):readonly JobDemandV1[]{return[...a].sort((x,y)=>x.id.localeCompare(y.id))}
function sf(a:readonly CandidateFactV1[]):readonly CandidateFactV1[]{return[...a].sort((x,y)=>x.id.localeCompare(y.id))}
function ok(i:EvidenceGraphBuildInputV1):void{if(!i?.userId||!i.applicationContextId||!Array.isArray(i.demands)||!Array.isArray(i.candidateFacts)||!Array.isArray(i.careerKnowledgeRules)||!Number.isFinite(i.createdAt))throw new TypeError("invalid EvidenceGraph input")}
