import type{CandidateFactV1}from"../candidate-evidence/schema";
import type{CareerKnowledgeRuleV1}from"../career-knowledge/schema";
import type{EvidenceGraphBuildInputV1,EvidenceRiskFlagCategoryV1,EvidenceRiskFlagSeverityV1,EvidenceRiskFlagV1,JobDemandV1}from"./schema";

const KEYS=new Set(["generatedText","polishedText","marketingCopy","finalCopy","proposalId","coverLetterId","generatedResumeId","generatedArtifactId"]);
const RULE:Partial<Record<EvidenceRiskFlagCategoryV1,string>>={generated_text_as_fact:"ck.v1.source_truth.generated_text_is_artifact_only",missing_evidence:"ck.v1.claim_safety.claims_need_source_support",never_use_fact:"ck.v1.source_truth.never_use_exclusion",private_fact:"ck.v1.source_truth.private_fact_exclusion",unsupported_certification:"ck.v1.claim_safety.no_unsupported_certifications",unsupported_language:"ck.v1.claim_safety.no_unsupported_language_proficiency",unsupported_metric:"ck.v1.claim_safety.no_invented_metrics"};
export function normalizeComparableText(v:string):string{return v.normalize("NFKC").trim().toLowerCase().replace(/[\u2018\u2019\u201c\u201d'"`.,;:!?()[\]{}<>/\\|_-]+/gu," ").replace(/\s+/gu," ").trim();}
export function slug(v:string):string{return normalizeComparableText(v).replace(/\s+/gu,"-")||"empty"}
export function extractCandidateFactTexts(f:CandidateFactV1):readonly string[]{const s=new Set<string>();add(s,f.normalizedText);add(s,f.sourceQuote);walk(s,f.value,0);return[...s].sort();}
export function getSourceGroundedClaimText(f:CandidateFactV1):string|undefined{return clean(f.normalizedText)||clean(f.sourceQuote)||firstValue(f.value)||extractCandidateFactTexts(f)[0];}
export function isApprovedUseInApplicationsFact(f:CandidateFactV1):boolean{return f.reviewState==="approved"&&f.visibility==="use_in_applications"&&!candidateFactLooksGeneratedText(f);}
export function candidateFactLooksGeneratedText(f:CandidateFactV1):boolean{return generatedPath(f.sourcePath)||generatedValue(f.value,new WeakSet<object>());}
export function determineFactDemandMatchType(d:JobDemandV1,f:CandidateFactV1):"direct"|"adjacent"|undefined{const dl=normalizeComparableText(d.label);const ft=extractCandidateFactTexts(f).map(normalizeComparableText);if(ft.includes(dl))return"direct";const dt=tokens(dl);return ft.some(t=>t.includes(dl)||dl.includes(t)||overlap(dt,tokens(t)))?"adjacent":undefined;}
export function buildRiskFlags(i:EvidenceGraphBuildInputV1):readonly EvidenceRiskFlagV1[]{const out=new Map<string,EvidenceRiskFlagV1>();const facts=[...i.candidateFacts].sort((a,b)=>a.id.localeCompare(b.id));const demands=[...i.demands].sort((a,b)=>a.id.localeCompare(b.id));for(const f of facts){if(f.visibility==="never_use")risk(out,i.careerKnowledgeRules,"never_use_fact","blocker","Fact is marked never_use.",f.id);if(candidateFactLooksGeneratedText(f))risk(out,i.careerKnowledgeRules,"generated_text_as_fact","blocker","Fact appears to contain generated polished text.",f.id);}for(const d of demands){const ms=facts.filter(f=>determineFactDemandMatchType(d,f));const ok=ms.some(isApprovedUseInApplicationsFact),blocked=ms.some(f=>f.visibility==="private"||f.visibility==="never_use");if(!ok&&!blocked)risk(out,i.careerKnowledgeRules,"missing_evidence",sev(d),"No approved use_in_applications fact supports this demand.",undefined,d.id);for(const f of ms){if(f.visibility==="private")risk(out,i.careerKnowledgeRules,"private_fact","blocker","Private fact matches this demand.",f.id,d.id);if(f.reviewState==="pending"||f.reviewState==="needs_review")risk(out,i.careerKnowledgeRules,"source_truth","warning","Matched fact is not approved.",f.id,d.id);if(f.reviewState==="rejected")risk(out,i.careerKnowledgeRules,"source_truth","blocker","Rejected fact matches this demand.",f.id,d.id);}if(!blocked&&d.kind==="certification"&&!ms.some(f=>f.factType==="certification"&&isApprovedUseInApplicationsFact(f)))risk(out,i.careerKnowledgeRules,"unsupported_certification",sev(d),"Certification demand lacks approved source evidence.",undefined,d.id);if(!blocked&&d.kind==="language"&&!ms.some(f=>f.factType==="language"&&isApprovedUseInApplicationsFact(f)))risk(out,i.careerKnowledgeRules,"unsupported_language",sev(d),"Language demand lacks approved source evidence.",undefined,d.id);if(!blocked&&metric(d)&&!ms.some(f=>isApprovedUseInApplicationsFact(f)&&hasNumber(f.value)))risk(out,i.careerKnowledgeRules,"unsupported_metric",sev(d),"Metric demand lacks source-backed numeric evidence.",undefined,d.id);}return[...out.values()].sort((a,b)=>a.id.localeCompare(b.id));}
function risk(m:Map<string,EvidenceRiskFlagV1>,rules:readonly CareerKnowledgeRuleV1[],category:EvidenceRiskFlagCategoryV1,severity:EvidenceRiskFlagSeverityV1,reason:string,candidateFactId?:string,demandId?:string){const r=RULE[category];const rule=r&&rules.some(x=>x.id===r)?r:undefined;const id=["evidence-graph-risk",category,demandId??"no-demand",candidateFactId??"no-fact",rule??"no-rule"].map(slug).join(":");if(!m.has(id))m.set(id,{id,category,severity,...candidateFactId?{candidateFactId}:{},...demandId?{demandId}:{},...rule?{careerKnowledgeRuleId:rule}:{},reason,version:1});}
function add(s:Set<string>,v:unknown){const c=clean(v);if(c)s.add(c)}function clean(v:unknown):string|undefined{return typeof v==="string"||typeof v==="number"?String(v).trim().replace(/\s+/gu," ")||undefined:undefined}
function walk(s:Set<string>,v:unknown,d:number){if(d>3||v==null)return;if(typeof v==="string"||typeof v==="number"){add(s,v);return}if(Array.isArray(v))for(const x of v)walk(s,x,d+1);else if(plain(v))for(const k of Object.keys(v).sort())walk(s,v[k],d+1)}
function firstValue(v:unknown):string|undefined{if(!plain(v))return;for(const k of["name","label","title","skill","language","certification","degree","responsibility","achievement","summary","description","value","role","company"]){const c=clean(v[k]);if(c)return c}}
function generatedPath(p:string){const t=normalizeComparableText(p.replace(/([a-z0-9])([A-Z])/gu,"$1 $2"));return t.includes("cover letter")||t.includes("generated resume")||t.includes("generated artifact")||t.includes("marketing copy")||t.includes("polished text")||t.includes("proposal")}
function generatedValue(v:unknown,seen:WeakSet<object>):boolean{if(!v||typeof v!=="object"||seen.has(v))return false;seen.add(v);if(Array.isArray(v))return v.some(x=>generatedValue(x,seen));return plain(v)&&Object.entries(v).some(([k,x])=>KEYS.has(k)||generatedValue(x,seen))}
function hasNumber(v:unknown):boolean{if(typeof v==="number")return Number.isFinite(v);if(typeof v==="string")return /\d/u.test(v);if(Array.isArray(v))return v.some(hasNumber);return plain(v)&&Object.values(v).some(hasNumber)}
function tokens(t:string){return normalizeComparableText(t).split(" ").filter(x=>x.length>2&&!["the","and","with","for","required","skill","experience"].includes(x))}
function overlap(a:string[],b:string[]){if(!a.length||!b.length)return false;const bs=new Set(b);return a.filter(x=>bs.has(x)).length/Math.min(a.length,b.length)>=.5}
function metric(d:JobDemandV1){return/\b(metric|measurable|numeric|number|percent|impact|revenue|growth|increase|reduce|improve|users|scale)\b|%/iu.test(d.label)}
function sev(d:JobDemandV1):EvidenceRiskFlagSeverityV1{return d.required==="required"?"blocker":d.required==="preferred"?"warning":"info"}function plain(v:unknown):v is Record<string,unknown>{return!!v&&typeof v==="object"&&!Array.isArray(v)&&(Object.getPrototypeOf(v)===Object.prototype||Object.getPrototypeOf(v)===null)}
