import{buildStableHash}from"../application-harness/fingerprints";
import type{AllowedClaimV1,EvidenceGraphV1,EvidenceMatchV1,EvidenceRiskFlagV1,JobDemandV1,MissingEvidenceV1}from"../evidence-graph/schema";
import{actionFromWarningSeverity,isClaimBackedResumeVariantPlanAction,isForbiddenResumeOrCoverLetterText,mapAllowedClaimTypeToResumeVariantPlanSection,mapJobDemandKindToResumeVariantPlanSection,mapRiskFlagCategoryToResumeVariantPlanWarningCategory,normalizePlanIdSegment,priorityFromWarningSeverity,reviewStateFromWarningSeverity,sortUniqueStrings,warningSeverityFromEvidenceSeverity}from"./planRules";
import type{BuildResumeVariantPlanInputV1,ResumeVariantPlanArtifactContentV1,ResumeVariantPlanItemV1,ResumeVariantPlanPriorityV1,ResumeVariantPlanV1,ResumeVariantPlanWarningV1}from"./schema";
const NS="resume-variant-plan",PREFIX="resume-variant-plan:",GP="evidence-graph:";
const RISKY=new Set(["private_fact","never_use_fact","generated_text_as_fact","source_truth"]);
type PlanNoId=Omit<ResumeVariantPlanV1,"id">;
export async function buildResumeVariantPlan(input:BuildResumeVariantPlanInputV1):Promise<ResumeVariantPlanV1>{assertInput(input);const items=buildResumeVariantPlanItems(input),warnings=buildResumeVariantPlanWarnings(input),blocked=warnings.some(w=>w.severity==="blocker"),blockedReason=blockedMsg(warnings);const base:PlanNoId={userId:input.userId,applicationContextId:input.applicationContextId,evidenceGraphId:input.evidenceGraph.id,evidenceGraphHash:graphHash(input.evidenceGraph),targetDocumentKind:input.targetDocumentKind,language:input.language,market:input.market,items,warnings,blockedClaimIds:sortUniqueStrings(input.evidenceGraph.blockedClaimIds),sourceFactIds:collectFactIds(items,warnings),allowedClaimIds:collectClaimIds(items),riskFlagIds:collectRiskIds(items,warnings),blocked,blockedReason,createdAt:input.createdAt,updatedAt:input.updatedAt,version:1};const plan:ResumeVariantPlanV1={id:`${PREFIX}${await buildResumeVariantPlanHash(input)}`,...base};assertResumeVariantPlanEvidenceBacked(plan,input.evidenceGraph);assertResumeVariantPlanDoesNotContainGeneratedText(plan);return plan}
export function buildResumeVariantPlanHash(inputOrPlan:BuildResumeVariantPlanInputV1|ResumeVariantPlanV1):Promise<string>{if(isInput(inputOrPlan)){assertInput(inputOrPlan);return buildStableHash({namespace:NS,type:"resume-variant-plan-input",version:1,input:{userId:inputOrPlan.userId,applicationContextId:inputOrPlan.applicationContextId,targetDocumentKind:inputOrPlan.targetDocumentKind,language:inputOrPlan.language,market:inputOrPlan.market,evidenceGraph:inputOrPlan.evidenceGraph,createdAt:inputOrPlan.createdAt,updatedAt:inputOrPlan.updatedAt}})}return buildStableHash({namespace:NS,type:"resume-variant-plan",version:1,plan:{...inputOrPlan,id:undefined}})}
export function buildResumeVariantPlanItems(input:BuildResumeVariantPlanInputV1):readonly ResumeVariantPlanItemV1[]{assertInput(input);const g=input.evidenceGraph,out:ResumeVariantPlanItemV1[]=[];for(const c of sortClaims(g.allowedClaims)){if(!usable(c,g))continue;const ms=matches(c,g);if(!ms.length)continue;const section=mapAllowedClaimTypeToResumeVariantPlanSection(c.claimType),candidateFactIds=sortUniqueStrings(c.candidateFactIds),demandIds=sortUniqueStrings(ms.map(m=>m.demandId)),evidenceMatchIds=sortUniqueStrings(ms.map(m=>m.id));out.push({id:["resume-variant-plan-item",section,"add-from-allowed-claim",c.id].map(normalizePlanIdSegment).join(":"),section,action:"add_from_allowed_claim",priority:priority(demandIds,g.demands),reviewState:"pending",allowedClaimIds:[c.id],candidateFactIds,evidenceMatchIds,demandIds,riskFlagIds:[],reason:`Add source-backed ${section} claim to ${section} section.`,version:1})}for(const m of sortMissing(g.missing))out.push(missingItem(m,g));for(const r of sortRisks(g.riskFlags))out.push(riskItem(r,g));return out.sort((a,b)=>a.id.localeCompare(b.id))}
export function buildResumeVariantPlanWarnings(input:BuildResumeVariantPlanInputV1):readonly ResumeVariantPlanWarningV1[]{assertInput(input);const out:ResumeVariantPlanWarningV1[]=[];for(const m of sortMissing(input.evidenceGraph.missing))out.push({id:["resume-variant-plan-warning","missing-evidence",m.id].map(normalizePlanIdSegment).join(":"),category:"missing_evidence",severity:warningSeverityFromEvidenceSeverity(m.severity),demandId:m.demandId,reason:m.reason,version:1});for(const r of sortRisks(input.evidenceGraph.riskFlags))out.push({id:["resume-variant-plan-warning",r.category,r.id].map(normalizePlanIdSegment).join(":"),category:mapRiskFlagCategoryToResumeVariantPlanWarningCategory(r.category),severity:warningSeverityFromEvidenceSeverity(r.severity),demandId:r.demandId,riskFlagId:r.id,candidateFactId:r.candidateFactId,reason:r.reason,version:1});return out.sort((a,b)=>a.id.localeCompare(b.id))}
export function buildResumeVariantPlanArtifactContent(plan:ResumeVariantPlanV1):ResumeVariantPlanArtifactContentV1{return{kind:"resume_variant_plan",plan,version:1}}
export function assertResumeVariantPlanEvidenceBacked(plan:ResumeVariantPlanV1,evidenceGraph:EvidenceGraphV1):void{const claims=new Map(evidenceGraph.allowedClaims.map(c=>[c.id,c])),byFact=acceptedByFact(evidenceGraph.matches),blocked=new Set(evidenceGraph.blockedClaimIds),risky=riskyFacts(evidenceGraph);for(const item of plan.items){if(!isClaimBackedResumeVariantPlanAction(item.action))continue;if(!item.allowedClaimIds.length)throw new Error(`Claim-backed plan item lacks allowedClaimIds: ${item.id}`);if(!item.candidateFactIds.length)throw new Error(`Claim-backed plan item lacks candidateFactIds: ${item.id}`);for(const id of item.allowedClaimIds){const claim=claims.get(id);if(!claim)throw new Error(`Plan item references unknown allowed claim: ${id}`);if(blocked.has(id))throw new Error(`Plan item references blocked claim: ${id}`);for(const f of claim.candidateFactIds){if(!item.candidateFactIds.includes(f))throw new Error(`Allowed claim does not map back to plan item fact: ${id}`);if(blocked.has(`blocked-claim:${f}`))throw new Error(`Plan item references fact from blocked claim: ${f}`)}}for(const f of item.candidateFactIds){if(risky.has(f))throw new Error(`Claim-backed plan item references excluded source fact: ${f}`);if(!(byFact.get(f)?.length))throw new Error(`Claim-backed plan item lacks accepted evidence match: ${f}`)}}}
export function assertResumeVariantPlanDoesNotContainGeneratedText(plan:ResumeVariantPlanV1):void{const values=[plan.blockedReason,...plan.items.map(i=>i.reason),...plan.warnings.map(w=>w.reason)].filter((x):x is string=>typeof x==="string");for(const v of values)if(isForbiddenResumeOrCoverLetterText(v))throw new Error("ResumeVariantPlan contains generated resume or cover-letter text")}
export function collectResumeVariantPlanSourceFactIds(plan:ResumeVariantPlanV1):readonly string[]{return collectFactIds(plan.items,plan.warnings)}
export function collectResumeVariantPlanAllowedClaimIds(plan:ResumeVariantPlanV1):readonly string[]{return collectClaimIds(plan.items)}
export function collectResumeVariantPlanRiskFlagIds(plan:ResumeVariantPlanV1):readonly string[]{return collectRiskIds(plan.items,plan.warnings)}
function missingItem(m:MissingEvidenceV1,g:EvidenceGraphV1):ResumeVariantPlanItemV1{const d=findDemand(g,m.demandId),section=d?mapJobDemandKindToResumeVariantPlanSection(d.kind):"other",action=actionFromWarningSeverity(m.severity);return{id:["resume-variant-plan-item",section,action,m.id].map(normalizePlanIdSegment).join(":"),section,action,priority:priorityFromWarningSeverity(m.severity),reviewState:reviewStateFromWarningSeverity(m.severity),allowedClaimIds:[],candidateFactIds:[],evidenceMatchIds:[],demandIds:[m.demandId],riskFlagIds:[],reason:m.severity==="blocker"?"Block plan until required missing evidence is reviewed.":"Flag missing evidence before resume planning.",version:1}}
function riskItem(r:EvidenceRiskFlagV1,g:EvidenceGraphV1):ResumeVariantPlanItemV1{const d=r.demandId?findDemand(g,r.demandId):undefined,section=d?mapJobDemandKindToResumeVariantPlanSection(d.kind):"other",action=actionFromWarningSeverity(r.severity);return{id:["resume-variant-plan-item",section,action,r.id].map(normalizePlanIdSegment).join(":"),section,action,priority:priorityFromWarningSeverity(r.severity),reviewState:reviewStateFromWarningSeverity(r.severity),allowedClaimIds:[],candidateFactIds:r.candidateFactId?[r.candidateFactId]:[],evidenceMatchIds:[],demandIds:r.demandId?[r.demandId]:[],riskFlagIds:[r.id],reason:reason(r),version:1}}
function reason(r:EvidenceRiskFlagV1):string{switch(r.category){case"private_fact":return"Block plan until private fact use is reviewed.";case"never_use_fact":return"Block plan because never_use facts cannot support a resume variant.";case"generated_text_as_fact":return"Block plan because artifact text cannot be treated as source evidence.";case"source_truth":return"Flag source-truth issue before resume planning.";case"missing_evidence":return r.severity==="blocker"?"Block plan until required missing evidence is reviewed.":"Flag missing evidence before resume planning.";case"unsupported_metric":case"unsupported_tool":case"unsupported_certification":case"unsupported_language":return"Flag unsupported claim before resume planning.";case"other":return"Flag evidence risk before resume planning."}}
function priority(ids:readonly string[],demands:readonly JobDemandV1[]):ResumeVariantPlanPriorityV1{const ds=demands.filter(d=>ids.includes(d.id));return ds.some(d=>d.required==="required")?"required":ds.some(d=>d.required==="preferred")?"recommended":"optional"}
function usable(c:AllowedClaimV1,g:EvidenceGraphV1):boolean{if(c.reviewState!=="allowed"||!c.candidateFactIds.length)return false;const b=new Set(g.blockedClaimIds);if(b.has(c.id)||c.candidateFactIds.some(id=>b.has(`blocked-claim:${id}`)))return false;const risky=riskyFacts(g);return !c.candidateFactIds.some(id=>risky.has(id))}
function matches(c:AllowedClaimV1,g:EvidenceGraphV1):readonly EvidenceMatchV1[]{const ids=new Set(c.candidateFactIds);return sortMatches(g.matches.filter(m=>ids.has(m.candidateFactId)&&m.reviewState==="accepted"))}
function acceptedByFact(ms:readonly EvidenceMatchV1[]):Map<string,readonly EvidenceMatchV1[]>{const out=new Map<string,EvidenceMatchV1[]>();for(const m of ms){if(m.reviewState!=="accepted")continue;const a=out.get(m.candidateFactId)??[];a.push(m);out.set(m.candidateFactId,a)}return new Map([...out.entries()].map(([k,v])=>[k,sortMatches(v)]))}
function riskyFacts(g:EvidenceGraphV1):Set<string>{return new Set(g.riskFlags.filter(r=>r.candidateFactId&&RISKY.has(r.category)).map(r=>r.candidateFactId).filter((id):id is string=>typeof id==="string"))}
function collectFactIds(items:readonly ResumeVariantPlanItemV1[],warnings:readonly ResumeVariantPlanWarningV1[]):readonly string[]{return sortUniqueStrings([...items.flatMap(i=>i.candidateFactIds),...warnings.map(w=>w.candidateFactId).filter((id):id is string=>typeof id==="string")])}
function collectClaimIds(items:readonly ResumeVariantPlanItemV1[]):readonly string[]{return sortUniqueStrings(items.flatMap(i=>i.allowedClaimIds))}
function collectRiskIds(items:readonly ResumeVariantPlanItemV1[],warnings:readonly ResumeVariantPlanWarningV1[]):readonly string[]{return sortUniqueStrings([...items.flatMap(i=>i.riskFlagIds),...warnings.map(w=>w.riskFlagId).filter((id):id is string=>typeof id==="string")])}
function blockedMsg(warnings:readonly ResumeVariantPlanWarningV1[]):string|undefined{const w=warnings.filter(x=>x.severity==="blocker").sort((a,b)=>a.id.localeCompare(b.id))[0];return w?`${w.category}: ${w.reason}`:undefined}
function graphHash(g:EvidenceGraphV1):string{return g.id.startsWith(GP)?g.id.slice(GP.length):g.id}
function findDemand(g:EvidenceGraphV1,id:string):JobDemandV1|undefined{return g.demands.find(d=>d.id===id)}
function sortClaims(a:readonly AllowedClaimV1[]):readonly AllowedClaimV1[]{return[...a].sort((x,y)=>x.id.localeCompare(y.id))}
function sortMatches(a:readonly EvidenceMatchV1[]):readonly EvidenceMatchV1[]{return[...a].sort((x,y)=>x.id.localeCompare(y.id))}
function sortMissing(a:readonly MissingEvidenceV1[]):readonly MissingEvidenceV1[]{return[...a].sort((x,y)=>x.id.localeCompare(y.id))}
function sortRisks(a:readonly EvidenceRiskFlagV1[]):readonly EvidenceRiskFlagV1[]{return[...a].sort((x,y)=>x.id.localeCompare(y.id))}
function isInput(x:BuildResumeVariantPlanInputV1|ResumeVariantPlanV1):x is BuildResumeVariantPlanInputV1{return"evidenceGraph"in x}
function assertInput(input:BuildResumeVariantPlanInputV1):void{if(!input||typeof input!=="object")throw new TypeError("invalid ResumeVariantPlan input");if(!input.userId||!input.applicationContextId)throw new TypeError("ResumeVariantPlan input requires userId and applicationContextId");if(input.targetDocumentKind!=="resume"&&input.targetDocumentKind!=="cv")throw new TypeError('ResumeVariantPlan targetDocumentKind must be "resume" or "cv"');if(!input.evidenceGraph?.id)throw new TypeError("ResumeVariantPlan input requires an EvidenceGraph");if(!Number.isFinite(input.createdAt)||!Number.isFinite(input.updatedAt))throw new TypeError("ResumeVariantPlan input requires numeric timestamps")}
