"""Add unique constraint to email

Revision ID: d232586d5a84
Revises: d9efe780a491
Create Date: 2025-08-27 21:05:54.443629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd232586d5a84'
down_revision: Union[str, Sequence[str], None] = 'd9efe780a491'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('llm_history', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_llm_history_convex_write_status'), 'llm_history', ['convex_write_status'], unique=False)
    op.alter_column('profiles', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('uq_profiles_email'), 'profiles', type_='unique')
    op.drop_index(op.f('ix_profiles_email'), table_name='profiles')
    op.create_index(op.f('ix_profiles_email'), 'profiles', ['email'], unique=True)
    op.drop_column('profiles', 'education')
    op.drop_column('profiles', 'achievements')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('achievements', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('education', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_profiles_email'), table_name='profiles')
    op.create_index(op.f('ix_profiles_email'), 'profiles', ['email'], unique=False)
    op.create_unique_constraint(op.f('uq_profiles_email'), 'profiles', ['email'])
    op.alter_column('profiles', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_llm_history_convex_write_status'), table_name='llm_history')
    op.alter_column('llm_history', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    # ### end Alembic commands ###
