import type { ResumeData } from "./resume.types";

export const resumeMock: ResumeData = {
  name: "Elena Marlowe",
  title: "Senior Product Designer",
  summary:
    "Editorially minded product designer with 9+ years shaping product systems, design language, and content-rich experiences across SaaS, commerce, and media. Known for translating ambiguity into calm, precise interfaces with strong narrative structure.",
  metadata: [
    { label: "Location", value: "Amsterdam, NL", itemId: "location" },
    { label: "Availability", value: "Open to leadership roles" },
    { label: "Portfolio", value: "elenamarlowe.design", itemId: "website" },
  ],
  contact: [
    {
      label: "Email",
      value: "elena@sample.design",
      itemId: "email",
      sectionId: "profile-1",
      sectionType: "profile",
    },
    {
      label: "Phone",
      value: "+31 6 5555 2381",
      itemId: "phone",
      sectionId: "profile-1",
      sectionType: "profile",
    },
    {
      label: "Web",
      value: "elenamarlowe.design",
      itemId: "website",
      sectionId: "profile-1",
      sectionType: "profile",
    },
    {
      label: "LinkedIn",
      value: "linkedin.com/in/elenamarlowe",
      itemId: "linkedin",
      sectionId: "profile-1",
      sectionType: "profile",
    },
  ],
  skills: [
    "Design direction",
    "Product strategy",
    "Interaction design",
    "Visual systems",
    "Editorial UI",
    "Research synthesis",
    "Prototyping",
    "Cross-functional leadership",
  ],
  skillItems: [
    "Design direction",
    "Product strategy",
    "Interaction design",
    "Visual systems",
    "Editorial UI",
    "Research synthesis",
    "Prototyping",
    "Cross-functional leadership",
  ].map((name, index) => ({
    id: `skill-${index + 1}`,
    name,
    sectionId: "skills-1",
    sectionType: "skills" as const,
    sectionTitle: "Skills",
    sectionOrder: 4,
  })),
  languages: [
    {
      id: "lang-1",
      name: "English",
      level: "Native",
      sectionId: "languages-1",
      sectionType: "languages",
      sectionTitle: "Languages",
      sectionOrder: 5,
    },
    {
      id: "lang-2",
      name: "Dutch",
      level: "Professional",
      sectionId: "languages-1",
      sectionType: "languages",
      sectionTitle: "Languages",
      sectionOrder: 5,
    },
    {
      id: "lang-3",
      name: "French",
      level: "Conversational",
      sectionId: "languages-1",
      sectionType: "languages",
      sectionTitle: "Languages",
      sectionOrder: 5,
    },
  ],
  experience: [
    {
      id: "exp-1",
      sectionId: "experience-1",
      sectionType: "experience",
      sectionTitle: "Experience",
      sectionOrder: 2,
      role: "Lead Product Designer",
      company: "Northline Studio",
      period: "2021 — Present",
      location: "Amsterdam",
      bullets: [
        "Led the redesign of a multi-market B2B platform, reducing workflow time by 28% through clearer information architecture and faster editorial navigation.",
        "Defined a visual system with content-first page patterns, typography scales, and reusable layout primitives adopted by three product squads.",
        "Partnered with product and engineering leadership to establish design review rituals, content QA, and rollout guidance for major releases.",
      ],
    },
    {
      id: "exp-2",
      sectionId: "experience-1",
      sectionType: "experience",
      sectionTitle: "Experience",
      sectionOrder: 2,
      role: "Senior Product Designer",
      company: "Signal House",
      period: "2018 — 2021",
      location: "Berlin",
      bullets: [
        "Designed publishing and analytics tools for editors and growth teams, balancing speed, legibility, and complex data workflows.",
        "Introduced component-level documentation and motion standards that improved implementation consistency across web and mobile.",
      ],
    },
    {
      id: "exp-3",
      sectionId: "experience-1",
      sectionType: "experience",
      sectionTitle: "Experience",
      sectionOrder: 2,
      role: "Product Designer",
      company: "Common Table",
      period: "2015 — 2018",
      location: "London",
      bullets: [
        "Delivered end-to-end features for marketplace discovery, booking, and account management with a strong focus on narrative merchandising.",
        "Worked closely with researchers to turn qualitative findings into journey-level service improvements and clearer transactional UI.",
      ],
    },
  ],
  projects: [
    {
      id: "project-1",
      sectionId: "projects-1",
      sectionType: "projects",
      sectionTitle: "Projects",
      sectionOrder: 6,
      name: "Atlas Design Language",
      meta: "System strategy · 2024",
      description:
        "Created a modular design language for dense product surfaces with article-like reading flow, semantic tokens, and print-aware documentation.",
    },
    {
      id: "project-2",
      sectionId: "projects-1",
      sectionType: "projects",
      sectionTitle: "Projects",
      sectionOrder: 6,
      name: "Editorial Commerce Toolkit",
      meta: "Experimentation platform · 2023",
      description:
        "Designed a toolkit for merchandisers to compose narrative product features, improving campaign velocity without sacrificing brand consistency.",
    },
  ],
  achievements: [
    "Reduced production time for new screens through a reusable design system.",
    "Improved clarity across dense workflows and editorially structured pages.",
    "Bridged product design and engineering with production-ready UI patterns.",
  ],
  achievementItems: [
    "Reduced production time for new screens through a reusable design system.",
    "Improved clarity across dense workflows and editorially structured pages.",
    "Bridged product design and engineering with production-ready UI patterns.",
  ].map((text, index) => ({
    id: `achievement-${index + 1}`,
    text,
    sectionId: "achievements-1",
    sectionType: "achievements" as const,
    sectionTitle: "Achievements",
    sectionOrder: 7,
  })),
  hobbies: ["Running", "Film photography"],
  hobbyItems: ["Running", "Film photography"].map((name, index) => ({
    id: `hobby-${index + 1}`,
    name,
    sectionId: "hobbies-1",
    sectionType: "hobbies" as const,
    sectionTitle: "Hobbies",
    sectionOrder: 10,
  })),

  education: [
    {
      id: "edu-1",
      sectionId: "education-1",
      sectionType: "education",
      sectionTitle: "Education",
      sectionOrder: 3,
      degree: "MA, Information Design",
      school: "University of the Arts London",
      period: "2013 — 2015",
    },
    {
      id: "edu-2",
      sectionId: "education-1",
      sectionType: "education",
      sectionTitle: "Education",
      sectionOrder: 3,
      degree: "BA, Visual Communication",
      school: "Kingston University",
      period: "2009 — 2013",
    },
  ],
  certifications: [
    {
      id: "cert-1",
      name: "Service Design Masterclass",
      issuer: "Nielsen Norman Group",
      meta: "Nielsen Norman Group · 2022",
      sectionId: "certifications-1",
      sectionType: "certifications",
      sectionTitle: "Certifications",
      sectionOrder: 8,
    },
  ],
  affiliations: [
    {
      id: "aff-1",
      organizationName: "IxDA Amsterdam",
      roleOrMembershipType: "Member",
      sectionId: "affiliations-1",
      sectionType: "affiliations",
      sectionTitle: "Affiliations",
      sectionOrder: 9,
    },
  ],
  textSections: [
    {
      id: "text-1",
      sectionId: "additional-information-1",
      sectionType: "additional_information",
      sectionTitle: "Additional Information",
      sectionOrder: 11,
      text: "Available for relocation across the EU and open to hybrid leadership roles.",
    },
  ],
  profileSectionId: "profile-1",
  summarySectionId: "summary-1",
  sectionIdsByType: {
    profile: ["profile-1"],
    summary: ["summary-1"],
    experience: ["experience-1"],
    education: ["education-1"],
    skills: ["skills-1"],
    languages: ["languages-1"],
    projects: ["projects-1"],
    achievements: ["achievements-1"],
    certifications: ["certifications-1"],
    affiliations: ["affiliations-1"],
    hobbies: ["hobbies-1"],
    additional_information: ["additional-information-1"],
  },
};
export const resumeMockOnecol: ResumeData = {
  name: "Elena Marlowe",
  title: "Senior Product Designer",
  summary:
    "Product designer shaping systems and content-rich interfaces.",
  metadata: [
    { label: "Location", value: "Amsterdam, NL", itemId: "location" },
    { label: "Portfolio", value: "elenamarlowe.design", itemId: "website" },
  ],
  contact: [
    {
      label: "Email",
      value: "hello@elenamarlowe.io",
      itemId: "email",
      sectionId: "profile-1",
      sectionType: "profile",
    },
    {
      label: "Phone",
      value: "+31 6 5555 2381",
      itemId: "phone",
      sectionId: "profile-1",
      sectionType: "profile",
    },
    {
      label: "Web",
      value: "elenamarlowe.io",
      itemId: "website",
      sectionId: "profile-1",
      sectionType: "profile",
    },
    {
      label: "LinkedIn",
      value: "linkedin.com/in/elenamarlowe",
      itemId: "linkedin",
      sectionId: "profile-1",
      sectionType: "profile",
    },
  ],
  skills: [
    "Design direction",
    "Product strategy",
    "Interaction design",
    "Visual systems",
    "Editorial UI",
    "Color theory",

  ],
  skillItems: [
    "Design direction",
    "Product strategy",
    "Interaction design",
    "Visual systems",
    "Editorial UI",
    "Color theory",
  ].map((name, index) => ({
    id: `skill-onecol-${index + 1}`,
    name,
    sectionId: "skills-1",
    sectionType: "skills" as const,
    sectionTitle: "Skills",
    sectionOrder: 4,
  })),
  languages: [
    {
      id: "lang-onecol-1",
      name: "English",
      level: "Fluent",
      sectionId: "languages-1",
      sectionType: "languages",
      sectionTitle: "Languages",
      sectionOrder: 5,
    },
    {
      id: "lang-onecol-2",
      name: "French",
      level: "Native",
      sectionId: "languages-1",
      sectionType: "languages",
      sectionTitle: "Languages",
      sectionOrder: 5,
    },
  ],
  experience: [
    {
      id: "exp-onecol-1",
      sectionId: "experience-1",
      sectionType: "experience",
      sectionTitle: "Experience",
      sectionOrder: 2,
      role: "Lead Product Designer",
      company: "Northline Studio",
      period: "2021 — Present",
      location: "Amsterdam",
      bullets: [
        "Led the redesign of a multi-market B2B platform, improving workflow clarity and editorial navigation.",
        "Defined a reusable visual system spanning page patterns, typography scales, and product primitives.",
      ],
    },
    {
      id: "exp-onecol-2",
      sectionId: "experience-1",
      sectionType: "experience",
      sectionTitle: "Experience",
      sectionOrder: 2,
      role: "Senior Product Designer",
      company: "Signal House",
      period: "2018 — 2021",
      location: "Berlin",
      bullets: [
        "Designed publishing and analytics tools for editors and growth teams across complex workflows.",
        "Introduced documentation and motion standards for more consistent implementation.",
      ],
    },
  
  ],
  projects: [],
  achievements: [
    "Reduced production time for new screens through a reusable design system.",
    "Improved clarity across dense workflows and editorial structures.",
  ],
  achievementItems: [
    "Reduced production time for new screens through a reusable design system.",
    "Improved clarity across dense workflows and editorial structures.",
  ].map((text, index) => ({
    id: `achievement-onecol-${index + 1}`,
    text,
    sectionId: "achievements-1",
    sectionType: "achievements" as const,
    sectionTitle: "Achievements",
    sectionOrder: 7,
  })),
  hobbies: ["Running", "Film photography"],
  hobbyItems: ["Running", "Film photography"].map((name, index) => ({
    id: `hobby-onecol-${index + 1}`,
    name,
    sectionId: "hobbies-1",
    sectionType: "hobbies" as const,
    sectionTitle: "Hobbies",
    sectionOrder: 10,
  })),
  education: [
    {
      id: "edu-onecol-1",
      sectionId: "education-1",
      sectionType: "education",
      sectionTitle: "Education",
      sectionOrder: 3,
      degree: "MA, Information Design",
      school: "University of the Arts London",
      period: "2013 — 2015",
    },
    {
      id: "edu-onecol-2",
      sectionId: "education-1",
      sectionType: "education",
      sectionTitle: "Education",
      sectionOrder: 3,
      degree: "BA, Visual Communication",
      school: "Kingston University",
      period: "2009 — 2013",
    },
  ],
  certifications: [],
  affiliations: [],
  textSections: [],
  profileSectionId: "profile-1",
  summarySectionId: "summary-1",
  sectionIdsByType: {
    profile: ["profile-1"],
    summary: ["summary-1"],
    experience: ["experience-1"],
    education: ["education-1"],
    skills: ["skills-1"],
    languages: ["languages-1"],
    achievements: ["achievements-1"],
    hobbies: ["hobbies-1"],
  },
};
