services:
  alembic:
    build:
      context: .
      dockerfile: Dockerfile.python311
    command: bash -c "alembic upgrade head"
    env_file:
      - .env.alembic
    volumes:
      - .:/app
    depends_on:
      - db
