import{describe,expect,it}from"vitest";
import{stableSerialize}from"../../application-harness/fingerprints";
import type{CandidateFactV1}from"../../candidate-evidence/schema";
import{listCareerKnowledgeRules}from"../../career-knowledge/resolver";
import{buildAllowedClaims,buildCandidateEvidenceSelectionHash,buildCareerKnowledgeSelectionHash,buildEvidenceGraph,buildEvidenceGraphHash,buildJobDemandGraphHash,buildMissingEvidence,matchCandidateFactsToDemands}from"../buildEvidenceGraph";
import{buildRiskFlags}from"../riskRules";
import type{EvidenceGraphBuildInputV1,JobDemandV1}from"../schema";
const T=Date.UTC(2026,5,9);
const rules=()=>listCareerKnowledgeRules();
function d(o:Partial<JobDemandV1>={}):JobDemandV1{return{id:"demand:typescript",kind:"skill",label:"TypeScript",required:"required",source:"job",sourcePath:"job.requirements[0]",weight:1,version:1,...o}}
function f(o:Partial<CandidateFactV1>={}):CandidateFactV1{return{id:"candidate-fact:typescript",userId:"user_123",sourceDocumentId:"candidate-source-document:source_hash_a",sourcePath:"document.skills[0].name",sourceQuote:"TypeScript",factType:"skill",value:{name:"TypeScript"},normalizedText:"TypeScript",confidence:.96,reviewState:"approved",visibility:"use_in_applications",createdAt:T,updatedAt:T,version:1,...o}}
function input(o:Partial<EvidenceGraphBuildInputV1>={}):EvidenceGraphBuildInputV1{return{userId:"user_123",applicationContextId:"application-context:abc",demands:[d()],candidateFacts:[f()],careerKnowledgeRules:rules(),createdAt:T,...o}}
describe("evidence-graph shadow module",()=>{
it("same input builds same EvidenceGraph hash",async()=>{const a=await buildEvidenceGraph(input()),b=await buildEvidenceGraph(input());expect(a.id).toBe(b.id);expect(a.id).toMatch(/^evidence-graph:[a-f0-9]{64}$/u);expect(await buildEvidenceGraphHash(input())).toBe(a.id.replace("evidence-graph:",""))});
it("changed demand changes graph hash",async()=>{expect(await buildEvidenceGraphHash(input({demands:[d({label:"React",id:"demand:react"})]}))).not.toBe(await buildEvidenceGraphHash(input()));expect(await buildJobDemandGraphHash([d()])).not.toBe(await buildJobDemandGraphHash([d({label:"React",id:"demand:react"})]))});
it("changed candidate fact changes graph hash",async()=>{const g=f({id:"candidate-fact:react",sourcePath:"document.skills[1].name",sourceQuote:"React",value:{name:"React"},normalizedText:"React"});expect(await buildEvidenceGraphHash(input({candidateFacts:[g]}))).not.toBe(await buildEvidenceGraphHash(input()));expect(await buildCandidateEvidenceSelectionHash([f()])).not.toBe(await buildCandidateEvidenceSelectionHash([g]))});
it("careerKnowledge selection hash is deterministic",async()=>{const r=rules();expect(await buildCareerKnowledgeSelectionHash(r)).toBe(await buildCareerKnowledgeSelectionHash([...r].reverse()))});
it("approved/use_in_applications fact creates allowed claim",async()=>{const g=await buildEvidenceGraph(input());expect(g.allowedClaims[0]).toMatchObject({candidateFactIds:["candidate-fact:typescript"],claimType:"skill",text:"TypeScript",reviewState:"allowed"});expect(buildAllowedClaims(input())).toHaveLength(1)});
it("pending fact does not create allowed claim",async()=>{const g=await buildEvidenceGraph(input({candidateFacts:[f({reviewState:"pending"})]}));expect(g.allowedClaims).toHaveLength(0);expect(g.matches[0]?.reviewState).toBe("pending");expect(g.blockedClaimIds).toEqual(["blocked-claim:candidate-fact:typescript"])});
it("rejected fact does not create allowed claim",async()=>{const g=await buildEvidenceGraph(input({candidateFacts:[f({reviewState:"rejected"})]}));expect(g.allowedClaims).toHaveLength(0);expect(g.matches[0]?.reviewState).toBe("rejected");expect(g.riskFlags.map(x=>x.category)).toContain("source_truth")});
it("never_use fact creates blocker risk and no allowed claim",async()=>{const g=await buildEvidenceGraph(input({candidateFacts:[f({visibility:"never_use"})]}));expect(g.allowedClaims).toHaveLength(0);expect(g.riskFlags).toEqual(expect.arrayContaining([expect.objectContaining({category:"never_use_fact",severity:"blocker",candidateFactId:"candidate-fact:typescript"})]));expect(g.riskFlags.map(x=>x.category)).not.toContain("missing_evidence")});
it("private fact creates risk and exclusion",async()=>{const g=await buildEvidenceGraph(input({candidateFacts:[f({visibility:"private"})]}));expect(g.allowedClaims).toHaveLength(0);expect(g.riskFlags).toEqual(expect.arrayContaining([expect.objectContaining({category:"private_fact",severity:"blocker",demandId:"demand:typescript",careerKnowledgeRuleId:"ck.v1.source_truth.private_fact_exclusion"})]));expect(g.riskFlags.map(x=>x.category)).not.toContain("missing_evidence")});
it("missing required demand creates missing evidence",async()=>{const g=await buildEvidenceGraph(input({candidateFacts:[]}));expect(g.missing).toEqual([{id:"missing-evidence:demand:typescript",demandId:"demand:typescript",label:"TypeScript",severity:"blocker",reason:"No approved source-backed evidence matched this demand.",version:1}]);expect(buildMissingEvidence(g.demands,g.matches)).toEqual(g.missing)});
it("unsupported certification risk is created",async()=>{const g=await buildEvidenceGraph(input({demands:[d({id:"demand:aws",kind:"certification",label:"AWS Certified Solutions Architect"})]}));expect(g.riskFlags).toEqual(expect.arrayContaining([expect.objectContaining({category:"unsupported_certification",demandId:"demand:aws",careerKnowledgeRuleId:"ck.v1.claim_safety.no_unsupported_certifications"})]))});
it("unsupported language risk is created",async()=>{const g=await buildEvidenceGraph(input({demands:[d({id:"demand:french",kind:"language",label:"French"})]}));expect(g.riskFlags).toEqual(expect.arrayContaining([expect.objectContaining({category:"unsupported_language",demandId:"demand:french",careerKnowledgeRuleId:"ck.v1.claim_safety.no_unsupported_language_proficiency"})]))});
it("sourceDocumentId and sourcePath are preserved in matches",()=>{expect(matchCandidateFactsToDemands(input())[0]).toMatchObject({candidateFactId:"candidate-fact:typescript",sourceDocumentId:"candidate-source-document:source_hash_a",sourcePath:"document.skills[0].name",matchType:"direct",reviewState:"accepted"})});
it("allowed claim text is source-grounded, not polished copy",async()=>{const g=await buildEvidenceGraph(input({demands:[d({id:"demand:migration",kind:"experience",label:"migration"})],candidateFacts:[f({id:"candidate-fact:migration",sourcePath:"document.experience[0].responsibilityBullets[0]",sourceQuote:"Led migration from legacy parser to structured profile data.",factType:"experience",value:{responsibility:"Led migration from legacy parser to structured profile data."},normalizedText:"Led migration from legacy parser to structured profile data."})]}));expect(g.allowedClaims[0]?.text).toBe("Led migration from legacy parser to structured profile data.");expect(g.allowedClaims[0]?.text).not.toMatch(/world-class|marketing/iu)});
it("generated polished text is blocked",async()=>{const g=await buildEvidenceGraph(input({candidateFacts:[f({id:"candidate-fact:generated",value:{generatedText:"World-class TypeScript expert who transforms businesses."},normalizedText:"TypeScript"})]}));expect(g.allowedClaims).toHaveLength(0);expect(g.riskFlags).toEqual(expect.arrayContaining([expect.objectContaining({category:"generated_text_as_fact",severity:"blocker",candidateFactId:"candidate-fact:generated"})]))});
it("metric demand without numeric source creates unsupported_metric risk",async()=>{const g=await buildEvidenceGraph(input({demands:[d({id:"demand:impact",kind:"responsibility",label:"measurable revenue impact"})],candidateFacts:[f({id:"candidate-fact:impact",factType:"achievement",value:{achievement:"Improved onboarding quality."},normalizedText:"Improved onboarding quality.",sourceQuote:"Improved onboarding quality."})]}));expect(g.riskFlags).toEqual(expect.arrayContaining([expect.objectContaining({category:"unsupported_metric",demandId:"demand:impact",careerKnowledgeRuleId:"ck.v1.claim_safety.no_invented_metrics"})]))});
it("helpers do not mutate inputs",async()=>{const i=input(),before=stableSerialize(i);await buildEvidenceGraph(i);await buildEvidenceGraphHash(i);matchCandidateFactsToDemands(i);buildRiskFlags(i);buildAllowedClaims(i);expect(stableSerialize(i)).toBe(before)});
it("output order is deterministic",async()=>{const rd=d({id:"demand:react",label:"React"}),td=d(),rf=f({id:"candidate-fact:react",sourcePath:"document.skills[1].name",sourceQuote:"React",value:{name:"React"},normalizedText:"React"}),tf=f();const a=await buildEvidenceGraph(input({demands:[rd,td],candidateFacts:[rf,tf]})),b=await buildEvidenceGraph(input({demands:[td,rd],candidateFacts:[tf,rf]}));expect(a.id).toBe(b.id);expect(a.demands.map(x=>x.id)).toEqual(["demand:react","demand:typescript"]);expect(a.matches.map(x=>x.id)).toEqual(b.matches.map(x=>x.id))});
it("CareerKnowledge rule IDs can appear on risk flags",()=>{expect(buildRiskFlags(input({candidateFacts:[f({visibility:"private"})]}))).toEqual(expect.arrayContaining([expect.objectContaining({category:"private_fact",careerKnowledgeRuleId:"ck.v1.source_truth.private_fact_exclusion"})]))});
});
