import{describe,expect,it}from"vitest";
import{stableSerialize}from"../../application-harness/fingerprints";
import type{CandidateFactV1}from"../../candidate-evidence/schema";
import{listCareerKnowledgeRules}from"../../career-knowledge/resolver";
import{buildEvidenceGraph}from"../../evidence-graph/buildEvidenceGraph";
import type{EvidenceGraphBuildInputV1,EvidenceGraphV1,JobDemandV1}from"../../evidence-graph/schema";
import{assertResumeVariantPlanDoesNotContainGeneratedText,assertResumeVariantPlanEvidenceBacked,buildResumeVariantPlan,buildResumeVariantPlanArtifactContent,buildResumeVariantPlanHash,buildResumeVariantPlanItems,buildResumeVariantPlanWarnings,collectResumeVariantPlanAllowedClaimIds,collectResumeVariantPlanRiskFlagIds,collectResumeVariantPlanSourceFactIds}from"../buildResumeVariantPlan";
import type{BuildResumeVariantPlanInputV1,ResumeVariantPlanV1}from"../schema";
const T=Date.UTC(2026,5,9);
const rules=()=>listCareerKnowledgeRules();
function d(o:Partial<JobDemandV1>={}):JobDemandV1{return{id:"demand:typescript",kind:"skill",label:"TypeScript",required:"required",source:"job",sourcePath:"job.requirements[0]",weight:1,version:1,...o}}
function f(o:Partial<CandidateFactV1>={}):CandidateFactV1{return{id:"candidate-fact:typescript",userId:"user_123",sourceDocumentId:"candidate-source-document:source_hash_a",sourcePath:"document.skills[0].name",sourceQuote:"TypeScript",factType:"skill",value:{name:"TypeScript"},normalizedText:"TypeScript",confidence:.96,reviewState:"approved",visibility:"use_in_applications",createdAt:T,updatedAt:T,version:1,...o}}
function evidenceInput(o:Partial<EvidenceGraphBuildInputV1>={}):EvidenceGraphBuildInputV1{return{userId:"user_123",applicationContextId:"application-context:abc",demands:[d()],candidateFacts:[f()],careerKnowledgeRules:rules(),createdAt:T,...o}}
async function planInput(o:Partial<BuildResumeVariantPlanInputV1>={},e:Partial<EvidenceGraphBuildInputV1>={}):Promise<BuildResumeVariantPlanInputV1>{const graph=o.evidenceGraph??await buildEvidenceGraph(evidenceInput(e));return{userId:"user_123",applicationContextId:"application-context:abc",targetDocumentKind:"resume",language:"en",market:"global",evidenceGraph:graph,createdAt:T,updatedAt:T,...o}}
describe("resume-variant-plan artifact",()=>{
it("same input builds same ResumeVariantPlan hash",async()=>{const input=await planInput(),a=await buildResumeVariantPlan(input),b=await buildResumeVariantPlan(input);expect(a.id).toBe(b.id);expect(a.id).toBe(`resume-variant-plan:${await buildResumeVariantPlanHash(input)}`);expect(a.id).toMatch(/^resume-variant-plan:[a-f0-9]{64}$/u)});
it("changed EvidenceGraph id, hash, or content changes plan hash",async()=>{const input=await planInput(),base=await buildResumeVariantPlanHash(input);const changedId={...input.evidenceGraph,id:"evidence-graph:changed"};const changedContent={...input.evidenceGraph,allowedClaims:[...input.evidenceGraph.allowedClaims,{...input.evidenceGraph.allowedClaims[0]!,id:"allowed-claim:candidate-fact:extra",candidateFactIds:["candidate-fact:extra"],text:"Extra",claimType:"skill" as const}]};await expect(buildResumeVariantPlanHash({...input,evidenceGraph:changedId})).resolves.not.toBe(base);await expect(buildResumeVariantPlanHash({...input,evidenceGraph:changedContent})).resolves.not.toBe(base)});
it("targetDocumentKind is preserved",async()=>{const plan=await buildResumeVariantPlan(await planInput({targetDocumentKind:"cv"}));expect(plan.targetDocumentKind).toBe("cv")});
it("approved allowed claim creates a pending plan item",async()=>{const plan=await buildResumeVariantPlan(await planInput());expect(plan.items).toEqual(expect.arrayContaining([expect.objectContaining({section:"skills",action:"add_from_allowed_claim",priority:"required",reviewState:"pending",allowedClaimIds:["allowed-claim:candidate-fact:typescript"]})]))});
it("plan item maps to allowedClaimIds and candidateFactIds",async()=>{const plan=await buildResumeVariantPlan(await planInput());const item=plan.items.find(x=>x.allowedClaimIds.length);expect(item).toMatchObject({allowedClaimIds:["allowed-claim:candidate-fact:typescript"],candidateFactIds:["candidate-fact:typescript"]})});
it("plan item preserves demandIds and evidenceMatchIds where available",async()=>{const input=await planInput(),plan=await buildResumeVariantPlan(input),item=plan.items.find(x=>x.allowedClaimIds.length)!;expect(item.demandIds).toEqual(["demand:typescript"]);expect(item.evidenceMatchIds).toEqual(input.evidenceGraph.matches.map(x=>x.id))});
it("missing evidence becomes a plan warning",async()=>{const input=await planInput({}, {candidateFacts:[]}),warnings=buildResumeVariantPlanWarnings(input);expect(warnings).toEqual(expect.arrayContaining([expect.objectContaining({category:"missing_evidence",severity:"blocker",demandId:"demand:typescript"})]))});
it("blocker risk sets blocked true",async()=>{const plan=await buildResumeVariantPlan(await planInput({}, {candidateFacts:[]}));expect(plan.blocked).toBe(true);expect(plan.blockedReason).toContain("missing_evidence")});
it("no blocker risk sets blocked false",async()=>{const plan=await buildResumeVariantPlan(await planInput());expect(plan.blocked).toBe(false);expect(plan.blockedReason).toBeUndefined()});
it("private_fact risk becomes a warning, not a claim-backed plan item",async()=>{const plan=await buildResumeVariantPlan(await planInput({}, {candidateFacts:[f({visibility:"private"})]}));expect(plan.warnings.map(x=>x.category)).toContain("private_fact");expect(plan.items.filter(x=>x.allowedClaimIds.length)).toHaveLength(0)});
it("never_use_fact risk becomes a warning, not a claim-backed plan item",async()=>{const plan=await buildResumeVariantPlan(await planInput({}, {candidateFacts:[f({visibility:"never_use"})]}));expect(plan.warnings.map(x=>x.category)).toContain("never_use_fact");expect(plan.items.filter(x=>x.allowedClaimIds.length)).toHaveLength(0)});
it("generated_text_as_fact risk becomes a warning, not a claim-backed plan item",async()=>{const plan=await buildResumeVariantPlan(await planInput({}, {candidateFacts:[f({id:"candidate-fact:generated",value:{generatedText:"World-class TypeScript expert who transforms businesses."}})]}));expect(plan.warnings.map(x=>x.category)).toContain("generated_text_as_fact");expect(plan.items.filter(x=>x.allowedClaimIds.length)).toHaveLength(0)});
it("blockedClaimIds are carried forward",async()=>{const input=await planInput({}, {candidateFacts:[f({reviewState:"pending"})]}),plan=await buildResumeVariantPlan(input);expect(plan.blockedClaimIds).toEqual(input.evidenceGraph.blockedClaimIds)});
it("no plan item is created from blocked claims",async()=>{const plan=await buildResumeVariantPlan(await planInput({}, {candidateFacts:[f({reviewState:"pending"})]}));expect(plan.items.filter(x=>x.allowedClaimIds.length)).toHaveLength(0)});
it("every include/emphasize/reorder/add_from_allowed_claim item is evidence-backed",async()=>{const input=await planInput(),plan=await buildResumeVariantPlan(input);expect(()=>assertResumeVariantPlanEvidenceBacked(plan,input.evidenceGraph)).not.toThrow()});
it("helper fails deterministically if a plan item lacks evidence backing",async()=>{const input=await planInput(),plan=await buildResumeVariantPlan(input);const bad:ResumeVariantPlanV1={...plan,items:[{...plan.items.find(x=>x.allowedClaimIds.length)!,allowedClaimIds:[]}]};expect(()=>assertResumeVariantPlanEvidenceBacked(bad,input.evidenceGraph)).toThrow(/lacks allowedClaimIds/u)});
it("no polished resume bullet text is produced",async()=>{const plan=await buildResumeVariantPlan(await planInput());expect(plan.items.map(x=>x.reason).join("\n")).not.toMatch(/increased revenue by 30%|world-class|proven track record/iu);expect(()=>assertResumeVariantPlanDoesNotContainGeneratedText(plan)).not.toThrow()});
it("no cover-letter text is produced",async()=>{const plan=await buildResumeVariantPlan(await planInput());expect([...plan.items.map(x=>x.reason),...plan.warnings.map(x=>x.reason)].join("\n")).not.toMatch(/dear hiring manager|excited to apply|sincerely/iu)});
it("artifact content helper returns kind resume_variant_plan",async()=>{const plan=await buildResumeVariantPlan(await planInput());expect(buildResumeVariantPlanArtifactContent(plan)).toMatchObject({kind:"resume_variant_plan",plan,version:1})});
it("collectors return sorted sourceFactIds, allowedClaimIds, and riskFlagIds",async()=>{const plan=await buildResumeVariantPlan(await planInput({}, {demands:[d({id:"demand:react",label:"React"}),d()],candidateFacts:[f({id:"candidate-fact:react",sourcePath:"document.skills[1].name",sourceQuote:"React",value:{name:"React"},normalizedText:"React"}),f()]}));expect(collectResumeVariantPlanSourceFactIds(plan)).toEqual(["candidate-fact:react","candidate-fact:typescript"]);expect(collectResumeVariantPlanAllowedClaimIds(plan)).toEqual(["allowed-claim:candidate-fact:react","allowed-claim:candidate-fact:typescript"]);expect(collectResumeVariantPlanRiskFlagIds(plan)).toEqual([])});
it("helpers do not mutate inputs",async()=>{const input=await planInput(),before=stableSerialize(input);buildResumeVariantPlanItems(input);buildResumeVariantPlanWarnings(input);await buildResumeVariantPlan(input);await buildResumeVariantPlanHash(input);expect(stableSerialize(input)).toBe(before)});
it("output order is deterministic",async()=>{const react=f({id:"candidate-fact:react",sourcePath:"document.skills[1].name",sourceQuote:"React",value:{name:"React"},normalizedText:"React"}),rd=d({id:"demand:react",label:"React"});const a=await buildResumeVariantPlan(await planInput({}, {demands:[rd,d()],candidateFacts:[react,f()]})),b=await buildResumeVariantPlan(await planInput({}, {demands:[d(),rd],candidateFacts:[f(),react]}));expect(a.id).toBe(b.id);expect(a.items.map(x=>x.id)).toEqual(b.items.map(x=>x.id))});
it("manual assertion blocks claim-backed items referencing private or generated facts",async()=>{const graph=await buildEvidenceGraph(evidenceInput());const riskyGraph:EvidenceGraphV1={...graph,riskFlags:[...graph.riskFlags,{id:"evidence-graph-risk:private-fact:no-demand:candidate-fact:typescript:no-rule",category:"private_fact",severity:"blocker",candidateFactId:"candidate-fact:typescript",reason:"Private fact matches this demand.",version:1}]};const plan=await buildResumeVariantPlan(await planInput({evidenceGraph:graph}));expect(()=>assertResumeVariantPlanEvidenceBacked(plan,riskyGraph)).toThrow(/excluded source fact/u)});
});
