"""add new column xyz

Revision ID: d41cf677615d
Revises: c24169e5416a
Create Date: 2025-08-27 11:04:36.488071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd41cf677615d'
down_revision: Union[str, Sequence[str], None] = 'c24169e5416a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # First, add the merged column if it doesn't exist (with nullable=True and default false)
    op.execute("ALTER TABLE llm_history ADD COLUMN IF NOT EXISTS merged BOOLEAN DEFAULT false")
    
    # Then alter the column to set NOT NULL
    op.alter_column('llm_history', 'merged',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('llm_history', 'convex_attempts',
               existing_type=sa.INTEGER(),
               server_default='0',
               existing_nullable=True)
    op.create_index(op.f('ix_llm_history_convex_idempotency_key'), 'llm_history', ['convex_idempotency_key'], unique=False)
    op.create_index(op.f('ix_llm_history_convex_write_status'), 'llm_history', ['convex_write_status'], unique=False)
    op.create_index(op.f('ix_llm_history_run_time'), 'llm_history', ['run_time'], unique=False)
    op.create_foreign_key(None, 'llm_history', 'profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.alter_column('profiles', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('profiles', 'name',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='User full name',
               existing_nullable=True)
    op.alter_column('profiles', 'email',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='User email address for identification and communication',
               existing_nullable=True)
    op.alter_column('profiles', 'summary',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Profile summary or bio',
               existing_nullable=True)
    op.alter_column('profiles', 'skills',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='List of skills as JSONB',
               existing_nullable=True)
    op.alter_column('profiles', 'experience',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Professional experience as JSONB',
               existing_nullable=True)
    op.alter_column('profiles', 'raw_text',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Original raw text used to generate profile',
               existing_nullable=True)
    op.alter_column('profiles', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Confidence score between 0 and 1',
               existing_nullable=True)
    op.alter_column('profiles', 'meta',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Additional metadata',
               existing_nullable=True)
    op.alter_column('profiles', 'version',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Versioning column for profile',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'version',
               existing_type=sa.INTEGER(),
               comment='Versioning column for profile',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('profiles', 'meta',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Additional metadata',
               existing_nullable=True)
    op.alter_column('profiles', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Confidence score between 0 and 1',
               existing_nullable=True)
    op.alter_column('profiles', 'raw_text',
               existing_type=sa.TEXT(),
               comment='Original raw text used to generate profile',
               existing_nullable=True)
    op.alter_column('profiles', 'experience',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Professional experience as JSONB',
               existing_nullable=True)
    op.alter_column('profiles', 'skills',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='List of skills as JSONB',
               existing_nullable=True)
    op.alter_column('profiles', 'summary',
               existing_type=sa.TEXT(),
               comment='Profile summary or bio',
               existing_nullable=True)
    op.alter_column('profiles', 'email',
               existing_type=sa.TEXT(),
               comment='User email address for identification and communication',
               existing_nullable=True)
    op.alter_column('profiles', 'name',
               existing_type=sa.TEXT(),
               comment='User full name',
               existing_nullable=True)
    op.alter_column('profiles', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_constraint(None, 'llm_history', type_='foreignkey')
    op.drop_index(op.f('ix_llm_history_run_time'), table_name='llm_history')
    op.drop_index(op.f('ix_llm_history_convex_write_status'), table_name='llm_history')
    op.drop_index(op.f('ix_llm_history_convex_idempotency_key'), table_name='llm_history')
    op.alter_column('llm_history', 'convex_attempts',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('llm_history', 'merged',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###
