// my-app/src/types/cvDocument.ts
import type { RemirrorJSON } from 'remirror';

/**
 * Primitive block types used within a CvSection.
 */
export type BlockType =
  | 'text'
  | 'heading'
  | 'list-item'
  | 'code'
  | 'image'
  | 'embed'
  | 'quote'
  | 'divider'
  | 'custom';

/**
 * Different section kinds in a CV document.
 */
export type SectionType =
  | 'text'
  | 'experience'
  | 'education'
  | 'skills'
  | 'languages'
  | 'projects'
  | 'certifications'
  | 'summary'
  | 'achievements'
  | 'contact'
  | 'profile';

/**
 * ISO 8601 date string (e.g. "2020-01-01" or full timestamp).
 * Use a central date utility to validate/normalize values before persistence.
 */
export type ISODateString = string;

/** Precision metadata for partial dates */
export type DatePrecision = 'year' | 'month' | 'day';

/** Generic 5-level scale for skills/languages (labels) */
export type Level = 'Beginner' | 'Elementary' | 'Intermediate' | 'Advanced' | 'Fluent';
export type SkillBucket = 'core' | 'secondary' | 'familiar';

/**
 * Represents a single, primitive block of content.
 */
export interface CvBlock {
  /** Optional during creation; populated when persisted (or generate a UUID in the client reducer). */
  id?: string;
  /** human readable optional title (some runtime schemas include this) */
  title?: string;
  type: BlockType;
  /** Remirror JSON content — make optional/loose to match runtime-validated Zod outputs */
  content?: RemirrorJSON | unknown;
  /** Derived, non-persistent plain text preview used for previews/search — recompute on demand, do not rely on this being persisted. */
  plainText?: string;
  /** order index inside the section */
  order?: number;
  /** extensible attributes for future use */
  attributes?: Record<string, unknown>;
}

/**
 * Experience item structure used in 'experience' sections.
 */
export interface IExperienceItem {
  /** Optional during client-side creation; persist will assign an id. */
  id?: string;
  company: string;
  position: string;
  startDate: ISODateString; // ISO 8601 date string
  endDate?: ISODateString | null;
  /** Preserve user-provided precision (optional for legacy) */
  startDatePrecision?: DatePrecision;
  endDatePrecision?: DatePrecision;
  /** Canonical ongoing flag for "Present" */
  isCurrent?: boolean;
  /** Legacy alias kept for backward compatibility */
  location?: string;
  responsibilities?: RemirrorJSON | string | string[];
  responsibilityBullets?: string[];
  /** Optional free-form description for experience (v1 modal) */
  description?: RemirrorJSON | string;
  achievements?: string[];
  currentlyWorking?: boolean;
}

/**
 * Education item structure used in 'education' sections.
 */
export interface IEducationItem {
  /** Optional during client-side creation; persist will assign an id. */
  id?: string;
  institution: string;
  degree?: string;
  fieldOfStudy?: string;
  startDate?: ISODateString;
  endDate?: ISODateString | null;
  /** Preserve user-provided precision (optional for legacy) */
  startDatePrecision?: DatePrecision;
  endDatePrecision?: DatePrecision;
  /** Allow ongoing studies (optional) */
  isCurrent?: boolean;
  grade?: string;
  description?: RemirrorJSON | string;
}

/** Profile (personal details) */
export interface IProfileItem {
  id?: string;
  name?: string;
  photoUrl?: string;
  email?: string;
  phone?: string;
  linkedin?: string;
  website?: string;
  desiredPosition?: string;
  location?: string;
}

/** Summary (free-text) */
export interface ISummaryItem {
  id?: string;
  summary?: RemirrorJSON | string;
}

/** Skill item (name + level) */
export interface ISkillItem {
  id?: string;
  name: string;
  level: Level;
  bucket?: SkillBucket;
}

/** Language item (name + level) */
export interface ILanguageItem {
  id?: string;
  name: string;
  level: Level;
}

/** Achievement item (id + text) — migrating from legacy string[] to structured objects */
export interface IAchievementItem {
  id?: string;
  text: string;
}

/**
 * Flexible content type for a section.
 */
export type SectionContent =
  | CvBlock[]
  | IExperienceItem[]
  | IEducationItem[]
  | ISkillItem[]
  | ILanguageItem[]
  | IAchievementItem[]
  | IProfileItem[]
  | ISummaryItem[]
  | RemirrorJSON
  | string[]
  | unknown;

/**
 * Represents a container for blocks, like "Experience" or "Education".
 *
 * Note: structuredContent takes precedence when present — use structuredContent for typed
 * sections (e.g., 'experience' or 'education'). The `blocks` array acts as a low-level
 * fallback representation and may be used for rendering or editing when structuredContent is absent.
 */
export interface CvSection {
  /** Optional during creation; set when persisted or generated by client reducer. */
  id?: string;
  title: string;
  type: SectionType;
  blocks: CvBlock[];
  /** structured content for specific section types (profile/summary/experience/education/skills/languages/achievements) */
  structuredContent?:
    | IExperienceItem[]
    | IEducationItem[]
    | ISkillItem[]
    | ILanguageItem[]
    | IAchievementItem[]
    | IProfileItem[]
    | ISummaryItem[]
    | string[]
    | null;
  /** UI state: collapsed in the editor */
  collapsed?: boolean;
  /** order of section in document */
  order?: number;
}

/**
 * Metadata for the CV document.
 */
export interface CvMetadata {
  createdAt: string; // ISO timestamp
  updatedAt: string; // ISO timestamp
  version: number;
  locale?: string;
  authorId?: string;
  lastEditedBy?: string;
  // Allow passthrough additional keys produced by runtime schema parsing (zod passthrough outputs)
  [k: string]: unknown;
}

/**
 * The root object for a CV document.
 */
export interface CvDocument {
  id: string;
  title: string;
  metadata: CvMetadata;
  sections: CvSection[];
  /** optional tags for search/filter */
  tags?: string[];
  /** optional overall summary (rich text or plain) */
  summary?: RemirrorJSON | string;
}
