from __future__ import annotations

RAW_SECTION_HEADING_ALIASES: dict[str, set[str]] = {
    "languages": {
        "language",
        "languages",
        "language skills",
        "languages spoken",
        "linguistic skills",
    },
    "skills": {
        "skills",
        "skill",
        "expertise",
        "areas of expertise",
        "area of expertise",
        "core competencies",
        "core competency",
        "technical skills",
        "key skills",
        "tech stack",
        "technical stack",
        "technical background",
        "capabilities",
        "key capabilities",
        "core skills",
        "tools",
        "technologies",
    },
    "achievements": {"achievements", "achievement", "accomplishments", "key achievements"},
    "experience": {
        "experience",
        "work experience",
        "professional experience",
        "employment history",
        "work history",
        "career history",
        "professional background",
        "relevant experience",
        "career experience",
        "industry experience",
        "experiencia",
        "experiencia laboral",
        "experiencia profesional",
        "historial laboral",
        "historial profesional",
        "trayectoria profesional",
        "experiencia profesional relevante",
        "experiência",
        "experiência profissional",
        "histórico profissional",
        "histórico de trabalho",
        "trajetória profissional",
        "expérience",
        "expérience professionnelle",
        "parcours professionnel",
        "historique professionnel",
        "expérience de travail",
        "berufserfahrung",
        "berufliche erfahrung",
        "beruflicher werdegang",
        "arbeitserfahrung",
        "werdegang",
        "esperienza",
        "esperienza professionale",
        "esperienza lavorativa",
        "percorso professionale",
    },
    "education": {"education", "academic background", "academic qualifications"},
    "summary": {"summary", "profile", "professional summary", "professional profile", "about"},
    "projects": {"projects", "project experience"},
    "certifications": {"certifications", "certification", "licenses", "licenses & certifications"},
    "awards": {"awards", "honors", "honours"},
    "publications": {"publications", "publication"},
    "volunteering": {"volunteering", "volunteer experience", "community involvement"},
    "hobbies": {"hobbies", "interests"},
    "affiliations": {"affiliations", "memberships"},
    "additionalInformation": {"additional information", "additional details"},
    "contact": {"contact", "contact information"},
}
