export const WORKSHOP_SECTION_TITLE_SIZE_REDUCTION_MM = 0.95;
export const WORKSHOP_EXPERIENCE_HEADING_SIZE_ADJUST_MM = 0.2;
export const WORKSHOP_EXPERIENCE_HEADING_LINE_HEIGHT = 1.25;
export const WORKSHOP_BOTTOM_FIT_SAFETY_MM = 0.5;
